### ISSUE TITLE
Xcode 9 this is not running on the latest version.

### ISSUE THREAD

**Issue by rodydavis** [mikegazzaruso/MySynth#1]
<img width="251" alt="screen shot 2017-11-17 at 7 24 19 pm" src="https://user-images.githubusercontent.com/31253215/32974532-f2742d44-cbcc-11e7-86a8-2ac07e8f4e34.png">

**Comment by mikegazzaruso** [comment]
Hi and sorry for the delay.

I've fixed some issues due to new AudioKit/AudioKitUI API Reference.

Please synchronize your repo with my last commit: https://github.com/mikegazzaruso/MySynth/commit/1aee8df8fb59ecd72e52849d226e015a98ce06cb

Thanks and Cheers,
____

Mike

**Comment by rodydavis** [comment]
Will do thank you!

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube
